# Generated by Django 4.0.2 on 2022-02-24 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_remove_blog_categories_alter_blog_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='categories',
            field=models.ManyToManyField(to='app_blog.Category'),
        ),
    ]
