# Generated by Django 4.0.2 on 2022-02-24 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_services', '0003_alter_service_created_alter_service_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
